# Generated by Django 6.0.3 on 2026-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('exception', 'Exception')], default='available', max_length=10),
        ),
    ]
