# Generated by Django 6.0.4 on 2026-04-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        ('appointment', '0002_add_check_in_time_and_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='appointment',
                to='slots.slot',
            ),
        ),
    ]

