# Generated by Django 6.0.3 on 2026-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_type',
            field=models.CharField(choices=[('working', 'Working Day'), ('off', 'Off Day')], max_length=7),
        ),
    ]
