# Generated by Django 6.0.3 on 2026-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_type',
            field=models.CharField(choices=[('working', 'Working Day'), ('off', 'Off Day'), ('exception', 'Exception')], default='working', max_length=10),
        ),
    ]
