# Generated by Django 6.0.3 on 2026-04-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
